# Generated by Django 3.2 on 2022-07-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_title', models.CharField(max_length=200)),
                ('membership_description', models.TextField()),
                ('membership_duration', models.CharField(max_length=2)),
                ('membership_start', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
